# Generated by Django 5.0.6 on 2024-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='/turismo/media/imgbd'),
        ),
    ]
