# Generated by Django 5.0.6 on 2024-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_alumno_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='turismo/media/imagenes', verbose_name='imagenes'),
        ),
    ]
